### ISSUE TITLE
Can't upload: Bad Request 400: File creation date cannot be modified.

### ISSUE THREAD

**Issue by philipp-roesch** [astrada/google-drive-ocamlfuse#159]
Since yesterday I can no longer upload files. **echo "abc" > f** will create a file of size 0, and I can't chmod or write to it. vim fails to write and returns Fsync error E667. cp fails with 'Device or resource busy'.

Tried so far:
1. updating all packages
2. deleting the .gdfuse directory & reauthorizing

**Comment by astrada** [comment]
Try using `-debug`, and then check the log files (`gdfuse.log` and `curl.log`) in `.gdfuse/default`. If you want, you can send them to my email: alessandro (dot) strada (at) gmail (dot) com

**Comment by brancomat** [comment]
Same thing here since yesterday (with the same effects of #160). `curl.log` shows a::
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "File creation date cannot be modified.",
    "locationType": "other",
    "location": "file.created_millis"
   }
  ],
  "code": 400,
  "message": "File creation date cannot be modified."
 }
}
```
from www.googleapis.com

**Comment by astrada** [comment]
If you are using OPAM, `opam update && opam upgrade` should fix this issue. I will upload a new Ubuntu package as soon as I can.

**Comment by philipp-roesch** [comment]
Fixed with gapi-ocaml.0.2.9.

**Comment by astrada** [comment]
Actually it doesn't fix the problem completely. The error is still there if file creation timestamp has a fractional part from 1 to 99 milliseconds. I will push another fix as soon as I can (tonight or tomorrow).

**Comment by officeutils** [comment]
A lot of thanks for your software. Waiting for updates too.

**Comment by astrada** [comment]
Should be fixed with gapi-ocaml 0.2.10

**Comment by brancomat** [comment]
It works for me! thanks

**Comment by philipp-roesch** [comment]
For me too. Thanks!

**Comment by kaoecoito** [comment]
I installed today by opam! It was installed version of google-drive-ocamlfuse 0.5.22 with 0.2.10 gapi-ocaml and still encounter the same error.
The log return

[253.890437] TID=0: BEGIN: Updating resource state in db (id=3137, state=Uploading)
[253.940902] TID=0: END: Updating resource state in db (id=3137)
[253.941137] TID=0: BEGIN: Uploading file (id=3137, path=/teste.txt, cache path=/root/.gdfuse/default/cache/0B-3JMDulqlGOeC1hUVlYcXIyVEU, content type=text/plain).
[255.409387] TID=0: ServiceError
[255.410040] TID=0: Exception:Failure("{\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"badRequest\",\"message\":\"File creation date cannot be modified.\",\"locationType\":\"other\",\"location\":\"file.created_millis\"}],\"code\":400,\"message\":\"File creation date cannot be modified.\"}}")

**Comment by astrada** [comment]
Can you please send `curl.log` to my email (alessandro.strada@gmail.com)? Thanks!

**Comment by kaoecoito** [comment]
I sent the log for you but I realized that although the Occam inform you that I already have the newest version of gapi-ocaml in the log it states that the used version is 0.2.8. Then I will delete everything that is installed the libs and try to install again to see if it with the correct version.
Thank you

**Comment by astrada** [comment]
OK, thanks for your feedback.

**Comment by kaoecoito** [comment]
It works now. Thanks

**Comment by foxy82** [comment]
How can I upgrade gapi-ocaml on Ubuntu? Is it a case of compiling it myself?

**Comment by foxy82** [comment]
Never mind - remoinv the PPA and readding it seemed to make it realise I didn't have the latest version.

**Comment by adamnovak** [comment]
It looks like the Ubuntu package for 12.04 in the PPA was never updated to fix this issue.

```
ls -lah `which google-drive-ocamlfuse`
-rwxr-xr-x 1 root root 3.2M Jan 16  2016 /usr/bin/google-drive-ocamlfuse

google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.5.22
Copyright (C) 2012-2016 Alessandro Strada
License MIT
```

I'm definitely having this problem, and I just installed the PPA today.

**Comment by astrada** [comment]
Unfortunately, to fix the bug, I needed to use an updated version of a library I'm using (libocamlnet-ocaml), but that version is not available in precise (you need version 3.5.1 or above, but the distribution has only version 3.4.1). So the fixed version won't build on Ubuntu 12.04.

**Comment by astrada** [comment]
If you cannot upgrade your system, your best option is to install the application using OPAM.

**Comment by adamnovak** [comment]
It definitely works via OPAM.

If 12.04 can't be fixed, it might make sense to take down the PPA for it,
so people don't think it's going to work.

On Fri, Sep 30, 2016 at 5:28 AM, Alessandro Strada <notifications@github.com

**Comment by astrada** [comment]
Right. I've removed obsolete packages from PPA.
