### ISSUE TITLE
fusermount -u leaves process behind

### ISSUE THREAD

**Issue by amclellan** [astrada/google-drive-ocamlfuse#313]
Hi,

I am using version 0.6.18 and it seems to work well. I mount a drive using

`google-drive-ocamlfuse -label ######## -skiptrash /mnt/########`

I un-mount it using

`fusermount -u /mnt/########`

However, when I check the process list with "ps" I find the "google-drive-ocamlfuse" is still there. Is this intentional or do I have a problem?

Many thanks,

Antony

**Comment by astrada** [comment]
It's a bug that I'm fixing in the next beta version, but it should be safe to just kill the process after unmounting (it's waiting for a thread that's not running).

**Comment by astrada** [comment]
Should be fixed in 0.6.20 (beta channel).

**Comment by quamis** [comment]
This is still happening in 

    $ google-drive-ocamlfuse -version
    google-drive-ocamlfuse, version 0.7.1
    Copyright (C) 2012-2018 Alessandro Strada
    License MIT


If it helps, it's an Ubuntu Server.
This is a problem for me, because I'm running a sort of backup process daily, for multiple accounts, and this will tend to leave lots of processes behind.

An news about the bug?

**Comment by astrada** [comment]
You should enable `-verbose` logging, then check what the application is doing during unmount (maybe sometimes your connection goes down?).

**Comment by quamis** [comment]
I've enabled verbose mode.
[gdfuse.log](https://github.com/astrada/google-drive-ocamlfuse/files/2991087/gdfuse.log)

![gd-left-running](https://user-images.githubusercontent.com/2966084/54737379-55f9a300-4bb8-11e9-9d1f-846a061616e1.png)

google-drive-ocamlfuse is still running after the sync process has finished.

**Comment by astrada** [comment]
I think that for a batch, you should probably set `metadata_memory_cache=false`, so the process doesn't have to wait for the background thread that writes to the cache db to end.

**Comment by quamis** [comment]
Yes, that seems to fix it, thanks. 

This config fixes my problem, but there might still be an issue present.
The config says that it `Enables in-memory metadata cache`. I wouldn't expect this to lead to a hanging process. In most cases there wouldn't be anything to cache, and there wasn't any disk IO anyway.

**Comment by astrada** [comment]
I'm sorry but I'm not able to reproduce it on my machine. It must be some kind of race condition that needs a condition setup to get triggered.

**Comment by quamis** [comment]
Is there anything I can send that might help?

**Comment by astrada** [comment]
Ho do you invoke the application? It's: mount, rsync, unmount? Is there any `sleep` commands in you script?

**Comment by quamis** [comment]
Hello,
something like:

```
google-drive-ocamlfuse -label "$GDRIVEACCOUNT" /root/googledrive/;
rsync -avzL --bwlimit=500 --chmod=uog=rwX --delete --backup ..... various paths .....
fusermount -u /root/googledrive/;
sleep 2;
```

**Comment by astrada** [comment]
Should be fixed in 0.7.6 (beta [ppa](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta)).
