### ISSUE TITLE
Cannot do anything in the .Trash folder

### ISSUE THREAD

**Issue by s-ilic** [astrada/google-drive-ocamlfuse#597]
Hi all,

I am able to use `google-drive-ocamlfuse` to mount my Drive folder successfully : but even though I am able to navigate the folders, list files, move/copy them, etc. without any issue, for some reason I am unable to do anything when I go inside the .Trash folder... Even a simple "ls" command causes my terminal to hang for a long time (up to an hour) until finally it unfreezes and output a 

> ls: cannot access '/home/myusername/gdrive/.Trash': Input/output error

Any idea why this is happening ? In case it's relevant, note that I am pretty sure that my Trash folder is very large (several tens of GB).

Thanks in advance !

Edit: you can find below the last 10000 lines of my logs after a typical I/O error, and my config file : 
[last_gdfuse.log](https://github.com/astrada/google-drive-ocamlfuse/files/4029029/last_gdfuse.log)
[last_curl.log](https://github.com/astrada/google-drive-ocamlfuse/files/4029030/last_curl.log)
[config.txt](https://github.com/astrada/google-drive-ocamlfuse/files/4029034/config.txt)

**Comment by astrada** [comment]
Thanks for the logs. Unfortunately there is no indication of an error. Can you check your full gdfuse.log and see if you can find the string "Exception"? Thanks!

**Comment by s-ilic** [comment]
Argh, sorry but I ended up deleting the log due to their very heavy size... I'll reproduce one as soon as possible. As a side note : when the terminal hangs (after I type "ls" for example), I can see from my system monitor (I'm using Linux Mint btw) that there is some incoming traffic to my computer, `google-drive-ocamlfuse` seems to be downloading some info...

Also, in the meantime I tried to use "rclone" to mount my Google Drive folder and see if I had the same problem with the trash folder, but everything went fine...

**Comment by s-ilic** [comment]
Alright, here's the full logs :
[curl.log](https://github.com/astrada/google-drive-ocamlfuse/files/4043833/curl.log)
[gdfuse.log](https://github.com/astrada/google-drive-ocamlfuse/files/4043838/gdfuse.log)


Only one occurence of "Exception" in the gdfuse.log :

> [312.517011] TID=606: Exception:Failure("{\"error\":{\"errors\":[{\"domain\":\"usageLimits\",\"reason\":\"rateLimitExceeded\",\"message\":\"Rate Limit Exceeded\"}],\"code\":403,\"message\":\"Rate Limit Exceeded\"}}")

So is this some error due to too many API calls triggering some blocking, or something  ?

**Comment by astrada** [comment]
Thanks! I thought I handled that error but probably failed. The problem is that it's not easy to reproduce. Anyway, I will look into it.

**Comment by s-ilic** [comment]
Thank you very much!

**Comment by astrada** [comment]
I think this should be fixed in version 0.7.16 that I'm publishing right now.

**Comment by s-ilic** [comment]
Humm.... I updated to 0.7.16, but the same issue is still there...

**Comment by astrada** [comment]
Can you please send your full logs to my email (alessandro.strada@gmail.com)? Thanks!

**Comment by astrada** [comment]
I think I fixed the issue in version 0.7.17.
